# -*- coding: utf-8 -*-
"""Airquality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ho-Qpn-RpKwStWMrVFA7kauJWRGGvMMu
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/sample_data/global air pollution dataset.csv")

data

data.info()

data.describe()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=data)
plt.title('Scatter Plot')
plt.show()

"""Preprocessing
1.handle missing values
2.remove Duplicate

"""

data.isnull().sum()

# 1. Remove rows where City is null
data = data[data['City'].notna()]

# 2. Replace missing Country with "Unknown"
data['Country'] = data['Country'].fillna("Unknown")

data.isnull().sum()

all_duplicates = data[data.duplicated(keep=False)]
print("\nAll duplicate rows:")
print(all_duplicates)

"""Feature Engineering

In some dataset or some values in AQI category may be wrong sometime, thus pollution levels from AQI values is created with standard rules
"""

def get_pollution_level(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Unhealthy for Sensitive"
    elif aqi <= 200:
        return "Unhealthy"
    elif aqi <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

data['Pollution_Level'] = data['AQI Value'].apply(get_pollution_level)

data.columns

"""dominant pollutant - Which pollutant is contributing the most to air pollution at a given place"""

def dominant_pollutant(row):
    pollutants = {
        "CO": row['CO AQI Value'],
        "Ozone": row['Ozone AQI Value'],
        "NO2": row['NO2 AQI Value'],
        "PM2.5": row['PM2.5 AQI Value']
    }
    return max(pollutants, key=pollutants.get)

data['Dominant_Pollutant'] = data.apply(dominant_pollutant, axis=1)

data.columns

data.head(3)

data.to_csv('processed_airqualityfile.csv', index=False)

